# Generated by Django 4.1.5 on 2023-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acidificacion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto', models.CharField(max_length=150, null=True, verbose_name='compuesto')),
                ('formula', models.CharField(max_length=150, null=True, verbose_name='formula')),
                ('pesoMolecular', models.FloatField(null=True, verbose_name='pesoMolecular')),
                ('fluor', models.PositiveIntegerField(null=True, verbose_name='fluor')),
                ('cloro', models.PositiveIntegerField(null=True, verbose_name='cloro')),
                ('nitrogeno', models.PositiveIntegerField(null=True, verbose_name='nitrogeno')),
                ('azufre', models.PositiveIntegerField(null=True, verbose_name='azufre')),
                ('potencialap', models.FloatField(null=True, verbose_name='potencialap')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Gwp',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto', models.CharField(max_length=150, null=True, verbose_name='compuesto')),
                ('formula', models.CharField(max_length=150, null=True, verbose_name='formula')),
                ('pesoMolecular', models.FloatField(null=True, verbose_name='pesoMolecular')),
                ('constantekOh', models.FloatField(null=True, verbose_name='constantekOh')),
                ('constantekCl', models.FloatField(null=True, verbose_name='constantekCl')),
                ('constantekO3', models.FloatField(null=True, verbose_name='constantekO3')),
                ('constantekNo3', models.FloatField(null=True, verbose_name='constantekNo3')),
                ('tiempoGlobalGwp', models.FloatField(null=True, verbose_name='tiempoGlobalGwp')),
                ('opticalPath', models.FloatField(null=True, verbose_name='=opticalPath')),
                ('concentration', models.FloatField(null=True, verbose_name='concentration')),
                ('globalWarming20', models.FloatField(null=True, verbose_name='globalWarming20')),
                ('globalWarming100', models.FloatField(null=True, verbose_name='globalWarming100')),
                ('globalWarming500', models.FloatField(null=True, verbose_name='globalWarming500')),
            ],
        ),
        migrations.CreateModel(
            name='Odp',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto', models.CharField(max_length=150, null=True, verbose_name='compuesto')),
                ('formula', models.CharField(max_length=150, null=True, verbose_name='formula')),
                ('pesoMolecular', models.FloatField(null=True, verbose_name='pesoMolecular')),
                ('constantekOh', models.FloatField(null=True, verbose_name='constantekOh')),
                ('constantekCl', models.FloatField(null=True, verbose_name='constantekCl')),
                ('constantekO3', models.FloatField(null=True, verbose_name='constantekO3')),
                ('constantekNo3', models.FloatField(null=True, verbose_name='constantekNo3')),
                ('tiempoGlobal', models.FloatField(null=True, verbose_name='tiempoGlobal')),
                ('numeroCloro', models.IntegerField(null=True, verbose_name='numeroCloro')),
                ('numeroBromo', models.IntegerField(null=True, verbose_name='numeroBromo')),
                ('potencialOdp', models.FloatField(null=True, verbose_name='potencialOdp')),
            ],
        ),
        migrations.CreateModel(
            name='Ozono',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto', models.CharField(max_length=150, null=True, verbose_name='compuesto')),
                ('formula', models.CharField(max_length=150, null=True, verbose_name='formula')),
                ('pesoMolecular', models.FloatField(null=True, verbose_name='pesoMolecular')),
                ('constantekOh', models.FloatField(null=True, verbose_name='constantekOh')),
                ('constantekO3', models.FloatField(null=True, verbose_name='constantekO3')),
                ('rendimientoCompuestoConOh', models.FloatField(null=True, verbose_name='rendimientoCompuestoConOh')),
                ('claseCov', models.CharField(max_length=150, null=True, verbose_name='claseCov')),
                ('region', models.CharField(max_length=150, null=True, verbose_name='region')),
                ('numeroEnlaces', models.PositiveIntegerField(null=True, verbose_name='numeroEnlaces')),
                ('numeroCarbonos', models.PositiveIntegerField(null=True, verbose_name='numeroCarbonos')),
                ('constantekOhProductoNoReactivo', models.FloatField(null=True, verbose_name='constantekOhProductoNoReactivo')),
                ('rendimientoProductoNoReactivo', models.FloatField(null=True, verbose_name='rendimientoProductoNoReactivo')),
                ('numeroEnlacesProducto', models.PositiveIntegerField(null=True, verbose_name='numeroEnlacesProducto')),
                ('claseCovP', models.CharField(max_length=150, null=True, verbose_name='claseCovP')),
                ('covsConOzono', models.CharField(max_length=150, null=True, verbose_name='covsConOzono')),
                ('covsAromatico', models.CharField(max_length=150, null=True, verbose_name='covsAromatico')),
                ('potencialPocp', models.FloatField(null=True, verbose_name='potencialPocp')),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto', models.CharField(max_length=150, null=True, verbose_name='compuesto')),
                ('formula', models.CharField(max_length=150, null=True, verbose_name='formula')),
                ('tiempoOh', models.FloatField(null=True, verbose_name='tiempoOh')),
                ('tiempoCl', models.FloatField(null=True, verbose_name='tiempoCl')),
                ('tiempoO3', models.FloatField(null=True, verbose_name='tiempoO3')),
                ('tiempoNo3', models.FloatField(null=True, verbose_name='tiempoNo3')),
            ],
        ),
    ]
